server:
  port: 6001

spring:
  application:
    name: cloud-order-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1
eureka:
  client:
    register-with-eureka: true # 表示是否将自己注册进EurekaServer 默认为 true
    fetch-registry: true # 是否从 EurekaServer 抓取已有的注册信息，默认 true，单节点无所谓，集群设置为true才能配合Ribbon使用负载均衡
    service-url:
            defaultZone: http://localhost:7001/eureka  # 单机版
#      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka  # 集群版
  instance:
    instance-id: consumer-order80
    prefer-ip-address: true          # 访问路径显示ip地址