server:
  port: 6001

spring:
  application:
    name: cloud-consumerconsul-order
  cloud: # consul 注册中心
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}

