server:
  port: 3344

spring:
  application:
    name: cloud-config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/tsubasatei/springcloud-config.git # Github上面的git仓库名字
#          uri: git@github.com:tsubasatei/springcloud-config.git # Github上面的git仓库名字, 访问不到 com.jcraft.jsch.JSchException: Auth fail
          search-paths:
            - springcloud-config  # 搜索目录
      label: master  # 读取分支
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka